package com.univapay.sdk.utils.mockcontent;

public class LedgersFakeRR {
  public static String getMerchantBalanceFakeResponse =
      "{\n"
          + "\"items\": [\n"
          + "    {\n"
          + "        \"id\": \"f8c86f7a-18f3-11e7-93ff-6feb8d2883ae\",\n"
          + "        \"store_id\": \"f1055366-18f3-11e7-ac9a-df664f5d7adc\",\n"
          + "        \"amount\": 3713,\n"
          + "        \"currency\": \"JPY\",\n"
          + "        \"amount_formatted\": 3713,\n"
          + "        \"percent_fee\": 5,\n"
          + "        \"flat_fee_amount\": 30,\n"
          + "        \"flat_fee_currency\": \"JPY\",\n"
          + "        \"flat_fee_formatted\": 30,\n"
          + "        \"exchange_rate\": 1,\n"
          + "        \"origin\": \"charge\",\n"
          + "        \"note\": \"some note\",\n"
          + "        \"created_on\": 1491282178808\n"
          + "    },\n"
          + "    {\n"
          + "        \"id\": \"f8dda07a-18f3-11e7-915f-7782f7d3f527\",\n"
          + "        \"store_id\": \"f1055366-18f3-11e7-ac9a-df664f5d7adc\",\n"
          + "        \"amount\": 74735,\n"
          + "        \"currency\": \"EUR\",\n"
          + "        \"amount_formatted\": 747.35,\n"
          + "        \"percent_fee\": 5,\n"
          + "        \"flat_fee_amount\": 30,\n"
          + "        \"flat_fee_currency\": \"EUR\",\n"
          + "        \"flat_fee_formatted\": 0.3,\n"
          + "        \"exchange_rate\": 1,\n"
          + "        \"origin\": \"charge\",\n"
          + "        \"note\": \"some note\",\n"
          + "        \"created_on\": 1491282178946\n"
          + "    },\n"
          + "    {\n"
          + "        \"id\": \"f8f2b65e-18f3-11e7-b4bf-2316639141b7\",\n"
          + "        \"store_id\": \"f1055366-18f3-11e7-ac9a-df664f5d7adc\",\n"
          + "        \"amount\": -417050,\n"
          + "        \"currency\": \"USD\",\n"
          + "        \"amount_formatted\": -4170.5,\n"
          + "        \"percent_fee\": 0,\n"
          + "        \"flat_fee_amount\": 0,\n"
          + "        \"flat_fee_currency\": \"USD\",\n"
          + "        \"flat_fee_formatted\": 0,\n"
          + "        \"origin\": \"refund\",\n"
          + "        \"exchange_rate\": 1,\n"
          + "        \"created_on\": 1491282179077\n"
          + "    },\n"
          + "    {\n"
          + "        \"id\": \"f93598e8-18f3-11e7-a608-077aef27c893\",\n"
          + "        \"store_id\": \"f105817e-18f3-11e7-9a97-273416246776\",\n"
          + "        \"amount\": 117675,\n"
          + "        \"currency\": \"EUR\",\n"
          + "        \"amount_formatted\": 1176.75,\n"
          + "        \"percent_fee\": 5,\n"
          + "        \"flat_fee_amount\": 30,\n"
          + "        \"flat_fee_currency\": \"EUR\",\n"
          + "        \"flat_fee_formatted\": 0.3,\n"
          + "        \"exchange_rate\": 1,\n"
          + "        \"origin\": \"charge\",\n"
          + "        \"note\": \"some note\",\n"
          + "        \"created_on\": 1491282179523\n"
          + "    },\n"
          + "    {\n"
          + "        \"id\": \"f95e4ab8-18f3-11e7-9a97-1b805cb61481\",\n"
          + "        \"store_id\": \"f105817e-18f3-11e7-9a97-273416246776\",\n"
          + "        \"amount\": 334845,\n"
          + "        \"currency\": \"USD\",\n"
          + "        \"amount_formatted\": 3348.45,\n"
          + "        \"percent_fee\": 5,\n"
          + "        \"flat_fee_amount\": 30,\n"
          + "        \"flat_fee_currency\": \"USD\",\n"
          + "        \"flat_fee_formatted\": 0.3,\n"
          + "        \"origin\": \"charge\",\n"
          + "        \"exchange_rate\": 1,\n"
          + "        \"created_on\": 1491282179790\n"
          + "    },\n"
          + "    {\n"
          + "        \"id\": \"f981f382-18f3-11e7-93ff-0ffc1e61aa70\",\n"
          + "        \"store_id\": \"f1054498-18f3-11e7-93ff-bb609c8f3ef7\",\n"
          + "        \"amount\": 482855,\n"
          + "        \"currency\": \"USD\",\n"
          + "        \"amount_formatted\": 4828.55,\n"
          + "        \"percent_fee\": 5,\n"
          + "        \"flat_fee_amount\": 30,\n"
          + "        \"flat_fee_currency\": \"USD\",\n"
          + "        \"flat_fee_formatted\": 0.3,\n"
          + "        \"exchange_rate\": 1,\n"
          + "        \"origin\": \"charge\",\n"
          + "        \"note\": \"some note\",\n"
          + "        \"created_on\": 1491282180023\n"
          + "    },\n"
          + "    {\n"
          + "        \"id\": \"f9909e5a-18f3-11e7-93ff-973b39de5b82\",\n"
          + "        \"store_id\": \"f1054498-18f3-11e7-93ff-bb609c8f3ef7\",\n"
          + "        \"amount\": 106,\n"
          + "        \"currency\": \"JPY\",\n"
          + "        \"amount_formatted\": 106,\n"
          + "        \"percent_fee\": 5,\n"
          + "        \"flat_fee_amount\": 30,\n"
          + "        \"flat_fee_currency\": \"JPY\",\n"
          + "        \"flat_fee_formatted\": 30,\n"
          + "        \"exchange_rate\": 1,\n"
          + "        \"origin\": \"charge\",\n"
          + "        \"created_on\": 1491282180120\n"
          + "    }\n"
          + "],\n"
          + "\"has_more\": false\n"
          + "}";

  public static String listLedgersFakeResponse =
      "{\n"
          + "   \"items\":[\n"
          + "      {\n"
          + "         \"id\":\"11e830a2-9e84-d536-900d-33098d1cb796\",\n"
          + "         \"store_id\":\"11e830a2-9da2-e1da-b639-3f7e371a527b\",\n"
          + "         \"amount\":98,\n"
          + "         \"currency\":\"JPY\",\n"
          + "         \"amount_formatted\":98,\n"
          + "         \"percent_fee\":3.5,\n"
          + "         \"flat_fee_amount\":30,\n"
          + "         \"flat_fee_currency\":\"JPY\",\n"
          + "         \"flat_fee_formatted\":30,\n"
          + "         \"exchange_rate\":105,\n"
          + "         \"origin\":\"charge\",\n"
          + "         \"created_on\":\"2018-03-26T12:06:03.713569+09:00\"\n"
          + "      },\n"
          + "      {\n"
          + "         \"id\":\"11e830a2-9e7f-4ce2-b034-1f7fbd426bdf\",\n"
          + "         \"store_id\":\"11e830a2-9da2-e1da-b639-3f7e371a527b\",\n"
          + "         \"amount\":98,\n"
          + "         \"currency\":\"EUR\",\n"
          + "         \"amount_formatted\":0.98,\n"
          + "         \"percent_fee\":3.5,\n"
          + "         \"flat_fee_amount\":30,\n"
          + "         \"flat_fee_currency\":\"EUR\",\n"
          + "         \"flat_fee_formatted\":0.3,\n"
          + "         \"exchange_rate\":105,\n"
          + "         \"origin\":\"charge\",\n"
          + "         \"created_on\":\"2018-03-26T12:06:03.677324+09:00\"\n"
          + "      }\n"
          + "   ],\n"
          + "   \"has_more\":false\n"
          + "}";
}
