package com.univapay.sdk.types;

import com.google.gson.annotations.SerializedName;

public enum Gateway {
  @SerializedName("payvision")
  PAYVISION,
  @SerializedName("wirecard")
  WIRECARD,
  @SerializedName("worldpay")
  WORLDPAY,
  @SerializedName("allied_wallet")
  ALLIED_WALLET,
  @SerializedName("allied_wallet_next_gen")
  ALLIED_WALLET_NEXT_GEN,
  @SerializedName("baltic_bill")
  BALTIC_BILL,
  @SerializedName("blu_sky")
  BLU_SKY,
  @SerializedName("nccc")
  NCCC,
  @SerializedName("meiko_pay")
  MEIKO_PAY,
  @SerializedName("first_data")
  FIRST_DATA,
  @SerializedName("alipay")
  ALIPAY,
  @SerializedName("qq")
  QQ,
  @SerializedName("pay_pay")
  PAY_PAY,
  @SerializedName("d_barai")
  D_BARAI,
  @SerializedName("alipay_merchant_qr")
  ALIPAY_MERCHANT_QR,
  @SerializedName("alipay_online")
  ALIPAY_ONLINE,
  @SerializedName("densan")
  DENSAN,
  @SerializedName("ips")
  IPS,
  @SerializedName("stratus")
  STRATUS,
  @SerializedName("paidy")
  PAIDY,
  @SerializedName("origami")
  ORIGAMI,
  @SerializedName("alipay_connect")
  ALIPAY_CONNECT,
  @SerializedName("we_chat")
  WE_CHAT,
  @SerializedName("jkopay")
  JKOPAY,
  @SerializedName("rakuten_pay")
  RAKUTEN_PAY,
  @SerializedName("bartong")
  BARTONG,
  @SerializedName("via")
  VIA,
  @SerializedName("merpay")
  MERPAY,
  @SerializedName("line_pay")
  LINE_PAY,
  @SerializedName("pay_pay_online")
  PAY_PAY_ONLINE,
  @SerializedName("au_pay")
  AU_PAY,
  @SerializedName("rakuten_pay_merchant")
  RAKUTEN_PAY_MERCHANT,
  @SerializedName("pay_pay_merchant")
  PAY_PAY_MERCHANT,
  @SerializedName("smart_checkout")
  SMART_CHECKOUT,
  @SerializedName("test")
  TEST
}
