package com.univapay.sdk.builders.qrcode;

import com.univapay.sdk.models.common.ChargeId;
import com.univapay.sdk.models.common.StoreId;
import com.univapay.sdk.models.response.QrCode;
import com.univapay.sdk.resources.QrMerchantsResource;
import retrofit2.Call;
import retrofit2.Retrofit;

public class QrCodeMerchantsBuilders {

  /**
   * Get the QrCode generated by the Gateway if available of a Charge using the
   * /stores/{storeId}/charges/{id}/qr route
   */
  public static class GetQrCodeMerchant
      extends AbstractQrCodeMerchantBuilders.AbstractGetQrCodeRequestBuilder<
          GetQrCodeMerchant, QrMerchantsResource, QrCode> {

    public GetQrCodeMerchant(Retrofit retrofit, StoreId storeId, ChargeId chargeId) {
      super(retrofit, storeId, chargeId);
    }

    @Override
    protected Call<QrCode> getRequest(QrMerchantsResource resource) {
      return resource.getChargeQrCodeMerchant(storeId, chargeId);
    }
  }
}
