package com.univapay.sdk.models.common;

import com.google.gson.annotations.SerializedName;
import com.univapay.sdk.models.request.transactiontoken.PaymentData;
import com.univapay.sdk.types.Gateway;
import com.univapay.sdk.types.PaymentTypeName;

public class ExternalCardPayment implements PaymentData {

  /** The external card gateway that processes the payment. */
  @SerializedName("gateway")
  private final Gateway gateway;

  /**
   * The merchant-supplied external reference locating the already-made charge in the gateway. This
   * is required: the reference is never generated by Univapay.
   */
  @SerializedName("gateway_transaction_id")
  private final String gatewayTransactionId;

  public ExternalCardPayment(Gateway gateway, String gatewayTransactionId) {
    this.gateway = gateway;
    this.gatewayTransactionId = gatewayTransactionId;
  }

  public Gateway getGateway() {
    return gateway;
  }

  public String getGatewayTransactionId() {
    return gatewayTransactionId;
  }

  @Override
  public PaymentTypeName getPaymentType() {
    return PaymentTypeName.EXTERNAL_CARD;
  }
}
