package com.univapay.sdk.models.response;

import com.google.gson.annotations.SerializedName;

/** Contains the Qr Code generated, for MPM Payments */
public class QrCode extends UnivapayResponse {

  @SerializedName("ready")
  private final boolean ready;

  @SerializedName("qr_image_url")
  private final String qrCode;

  public QrCode(boolean ready, String qrCode) {
    this.ready = ready;
    this.qrCode = qrCode;
  }

  /**
   * The value to be displayed in a QrCode, generated by the Gateway
   *
   * @return string representation, usually a URL, null if not generated yet
   */
  public String getQrCode() {
    return qrCode;
  }

  /**
   * Represents if is a state that can be displayed and processed
   *
   * @return true if the Charge status is AWAITING
   */
  public boolean isReady() {
    return ready;
  }
}
